apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  clusterIP: 10.3.248.204
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: frontend
