apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubuntu
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: ubuntu
    spec:
      containers:
      - name: bash
        image: eu.gcr.io/proven-outpost-114117/netconomy-frontend-stub:0.6
        command:
          - sleep
          - "3600"
