apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: nginx
        image: eu.gcr.io/proven-outpost-114117/netconomy-proxy-nginx:0.6
        ports:
        - containerPort: 80
        env:
        - name: FRONTEND_IP
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: frontend_ip
      - name: haproxy
        image: eu.gcr.io/proven-outpost-114117/netconomy-proxy-haproxy:0.4
        volumeMounts:
        - name: haproxy-config
          mountPath: /etc/haproxy/
      - name: kube2haproxy
        image: eu.gcr.io/proven-outpost-114117/netconomy-proxy-kube2haproxy:0.4
        volumeMounts:
        - name: haproxy-config
          mountPath: /etc/haproxy/
      volumes:
      - name: haproxy-config
        emptyDir: {}
